// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFbBi1PfGyE6mHCcjuLzuZk93LkPCX6Mg',
    appId: '1:927206952114:web:71c3a8c210e1e201d88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    authDomain: 'heartlink-dating-project.firebaseapp.com',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
    measurementId: 'G-N35LDY7EXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhds0TxN-XUh1k5MAMbVeUbc5zV71y6no',
    appId: '1:927206952114:android:5bb7b966a0c78aa0d88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOFoduumROHE0FLuZ-e0rrHrYd8Gmx9Q',
    appId: '1:927206952114:ios:3fc1e19458c71b7fd88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
    androidClientId: '927206952114-73lagmaoh9j4lqpi8pjrep5evsshjssk.apps.googleusercontent.com',
    iosClientId: '927206952114-g9rgdnvg59ccemmpp7k7hofdpilc7624.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyOFoduumROHE0FLuZ-e0rrHrYd8Gmx9Q',
    appId: '1:927206952114:ios:3fc1e19458c71b7fd88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
    androidClientId: '927206952114-73lagmaoh9j4lqpi8pjrep5evsshjssk.apps.googleusercontent.com',
    iosClientId: '927206952114-g9rgdnvg59ccemmpp7k7hofdpilc7624.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFbBi1PfGyE6mHCcjuLzuZk93LkPCX6Mg',
    appId: '1:927206952114:web:71c3a8c210e1e201d88dab',
    messagingSenderId: '927206952114',
    projectId: 'heartlink-dating-project',
    authDomain: 'heartlink-dating-project.firebaseapp.com',
    databaseURL: 'https://heartlink-dating-project-default-rtdb.firebaseio.com',
    storageBucket: 'heartlink-dating-project.appspot.com',
    measurementId: 'G-N35LDY7EXG',
  );
}
